GET https://server-dep.vercel.app/
###

GET https://server-dep.vercel.app/data/ashok
###

POST http://localhost:5000/posting/
Content-Type: application/json

{
    "name":"Tulasi",
    "pass":"rocktulasi@2021"
}
###

GET http://localhost:5000/user/data